# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'landing_page_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Login_Page import Ui_Login_Window
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Landing_Page(object):

    def setupUi(self, Landing_Page):

        def start_button_clicked():
            self.Landing_Page = QtWidgets.QMainWindow()
            self.ui = Ui_Login_Window()
            self.ui.setupUi(self.Landing_Page)
            Landing_Page.hide()
            self.Landing_Page.show()

        Landing_Page.setObjectName("Landing_Page")
        Landing_Page.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Landing_Page.setFixedSize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Landing_Page.sizePolicy().hasHeightForWidth())
        Landing_Page.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Landing_Page.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Landing_Page)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/landing_page.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(990, 600, 220, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_button.setMouseTracking(True)
        self.start_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.start_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-style: none;\n"
"    border-radius: 25px;\n"
"    color: rgb(13, 14, 40);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(0, 0, 63);    \n"
"    border-radius: 25px;\n"
"    color: rgb(47, 47, 47);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(13, 14, 40);\n"
"    border-style: none;\n"
"    border-radius: 25px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.start_button.setAutoDefault(False)
        self.start_button.setDefault(False)
        self.start_button.setFlat(False)
        self.start_button.setObjectName("start_button")
        self.start_button.clicked.connect(start_button_clicked)
        Landing_Page.setCentralWidget(self.centralwidget)

        self.retranslateUi(Landing_Page)
        QtCore.QMetaObject.connectSlotsByName(Landing_Page)

    def retranslateUi(self, Landing_Page):
        _translate = QtCore.QCoreApplication.translate
        Landing_Page.setWindowTitle(_translate("Landing_Page", "Login Page"))
        self.start_button.setText(_translate("Landing_Page", "GET STARTED"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Landing_Page = QtWidgets.QMainWindow()
    ui = Ui_Landing_Page()
    ui.setupUi(Landing_Page)
    Landing_Page.show()
    sys.exit(app.exec_())
